
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

ignored = ["github.com/Sirupsen/logrus", "github.com/gravitational/license/generate*", "github.com/gravitational/license/authority*", "github.com/cloudflare/cfssl*"]

[prune]
  go-tests = true
  unused-packages = true
  non-go = true

[[constraint]]
  name = "github.com/gravitational/teleport"
  version = "4.2.2"

[[constraint]]
  name = "github.com/gravitational/kingpin"
  revision = "742f2714c145075a68df26ccc25bc05545310f3a"

[[constraint]]
  name = "google.golang.org/grpc"
  version = ">=1.23.0"

[[constraint]]
  name = "github.com/gravitational/trace"
  version = "1.1.6"

[[override]]
  name = "github.com/sirupsen/logrus"
  source = "github.com/gravitational/logrus"
  version = "1.0.0"

[[constraint]]
  name = "github.com/nlopes/slack"
  source = "github.com/marshall-lee/slack"
  branch = "slacktest-fixes"

# Teleport dependencies overrides

[[override]]
  name = "github.com/prometheus/procfs"
  version = "v0.0.2"

[[override]]
  name = "github.com/alecthomas/template"
  branch = "master"

[[override]]
  name = "github.com/alecthomas/units"
  branch = "master"

[[override]]
  name = "github.com/cenkalti/backoff"
  version = ">=1.0.0, <=19.0.0-g5d150e7"

[[override]]
  name = "k8s.io/api"
  branch = "release-1.9"

[[override]]
  name = "k8s.io/apimachinery"
  branch = "release-1.9"

[[override]]
  name = "github.com/iovisor/gobpf"
  source = "github.com/gravitational/gobpf"
  version = "=v0.0.1"

